version: '3'
services:
  piwigo:
    container_name: piwigo
    image: piwigo-docker
    ports:
      - "8000:8000"

  mysql:
    container_name: piwigo_mysql
    image: mysql:8.0.18
    command: ["--default-authentication-plugin=mysql_native_password"]
    environment:
      MYSQL_USER: "piwigo"
      MYSQL_PASSWORD: "piwigo"
      MYSQL_DATABASE: "piwigo"
      MYSQL_RANDOM_ROOT_PASSWORD: "true"

